databases:
  - name: donotmiss-db
    plan: free
    databaseName: donotmiss
    user: donotmiss

services:
  - type: web
    name: donotmiss-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: donotmiss-db
          property: connectionString
